name: lore_editor
description: Text editor abstractions and widgets for Lore.
publish_to: none

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0

flutter:
