name: lore_application
description: Application use cases and ports for Lore.
publish_to: none

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  lore_domain:
    path: ../lore_domain

dev_dependencies:
  test: ^1.26.3
