name: lore_storage
description: Local storage adapters for Lore.
publish_to: none

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  crypto: ^3.0.7
  lore_application:
    path: ../lore_application
  lore_domain:
    path: ../lore_domain
  path: ^1.9.1
  uuid: ^4.5.2

dev_dependencies:
  test: ^1.25.0
